spring:

    h2:
        console:
            enabled: true
            path: /h2

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password


    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 100MB
    application:
        name: stt-api
    liquibase:
        change-log: classpath:/db/changelog/changelog-master.xml
        enabled: true

server:
    port: 8080
    connection-timeout: 200





