spring:
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 100MB
    application:
        name: stt-api
server:
    port: 8080
    connection-timeout: 200








